### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by egichuhis** [egichuhis/space-travelers-hub#25]
Hello, please review this Group Project Kanban Board.

Note: There are 2 members in this team. We have assigned the tasks accordingly. 
Here is the [LINK](https://github.com/egichuhis/space-travelers-hub/projects/1
) to the Kanban board for your review.

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @egichuhis and @erickma1,

✔️ Tasks are well assigned

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit:
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by egichuhis** [comment]
Thanks @TedLivist
